import axios from "axios";

const API_URL = `https://api.mission4us.com/api/providers?updateLanguages=true&updateJobs=true&updateDriverLicences=true&updateExperiences=true&updat
eSkills=true`;

 
const api = async (obj,token) => {

  let tp ="eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJqOVE4S1dhaXNqT05OZjN5QWZtRGxHaFhaSkVmOFF6anNUZFZ3ZGdSQTk0In0.eyJleHAiOjE2ODM2NDY1MDcsImlhdCI6MTY4MzY0NjIwNywianRpIjoiOGUwYWYyMzQtYzNmZS00OGY4LWEzYmMtMDI4M2MwOGMxNjZiIiwiaXNzIjoiaHR0cHM6Ly9hdXRoLm1pc3Npb240dXMuY29tL2F1dGgvcmVhbG1zL2xvY2FsX3Rlc3RzIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6IjBiMGQ2YmQ0LTg1N2ItNDFiZS04MmMwLTQ3YmM5MGZmMDE5OCIsInR5cCI6IkJlYXJlciIsImF6cCI6Im00dXNfdGVzdHMiLCJzZXNzaW9uX3N0YXRlIjoiYzZjZDQ2NGQtOGZmNC00MDk5LTliYWMtYzI4ZTIwZGRhY2UzIiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6WyIqIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsImRlZmF1bHQtcm9sZXMtbG9jYWxfdGVzdHMiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7Im00dXNfdGVzdHMiOnsicm9sZXMiOlsiUk9MRV9QUk9WSURFUiJdfSwiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwic2lkIjoiYzZjZDQ2NGQtOGZmNC00MDk5LTliYWMtYzI4ZTIwZGRhY2UzIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJyb2xlcyI6WyJST0xFX1BST1ZJREVSIl0sIm5hbWUiOiJCZWtrYSBBZGFtIiwicHJlZmVycmVkX3VzZXJuYW1lIjoiYWRhbSIsImdpdmVuX25hbWUiOiJCZWtrYSIsImZhbWlseV9uYW1lIjoiQWRhbSIsImVtYWlsIjoiYWRhbUBnbWFpbC5jb20ifQ.TXZOEyqYGrqXzDn5wNhAhobeux-KlzLgPBNh0FBplqpL7R3E2RdLFyZPf9K13kn8eTsQwadoNdOIaLz4XoJJLir1lNEJzpZLABEUiQSzXbaG8O3ru6mao9vMivhG5aJKKCHyv25sb2AWfXs1NQJEjAiLUjKO0lvUTQ4dsTWCrZ2ycrbsrE5YYtEjTkanH64McKffRqs1ktLmKZSIGuOyiH92qcSrEBFYYHbtEDdQYVPz0sNHEOWVQ2RndItZvjRbOnt8YGmgw2skJy6sq1FGlCWGtxpN9R238X8fvHX3hHitcJTdfFrqZzZDuJZQ4smbVmjrEACQDCZbD8CHd745Hw"
 
  const config = {
    headers: {
      Authorization: `Bearer ${token}`,
    },
  };

  const res = await axios.put(API_URL,obj, config);
  return res;
};
const CreateCvService = {
  api,
};
export default CreateCvService;
